# Unit 12: Master Viva-Voce Defense Companion (30 Architectural Q&As)

def add_viva_defense(b):
    b.unit_header("12", "Master Viva-Voce Defense Companion (30 Architectural Q&As)")
    b.anchor("Acing the External University & Enterprise Architectural Defense",
             "To prepare the candidate with authoritative, bulletproof answers to the most challenging questions an external examiner or chief architect will pose.",
             "Prevents hesitation, ambiguous responses, and scoring penalties during major project viva-voce examination.")

    viva_qa = [
        ("What is the core thesis of UNPLUG?",
         "UNPLUG is not a casual gaming website; it is an enterprise software delivery, release governance, and runtime containment platform that uses HTML5 canvas mini-games as lightweight demonstration payloads to prove zero-trust sandboxing, cryptographic verification, and instant rollback."),
        ("Why is a SHA-256 hash insufficient for software release authorization?",
         "SHA-256 only guarantees data integrity (detecting unintentional bit rot or transmission corruption). It does not guarantee authenticity or provenance. An attacker who modifies code can easily recompute a matching hash. An asymmetric digital signature (ECDSA P-256) proves that the release was signed by the legitimate publisher possessing the private signing key."),
        ("How does UNPLUG isolate untrusted third-party code from the host platform?",
         "Through a defense-in-depth model: (1) Dual-port origin separation (Port 3000 player vs. Port 3001 admin), (2) An iframe configured strictly with sandbox='allow-scripts' without 'allow-same-origin', and (3) A Content Security Policy restricting connect-src 'none' to block network exfiltration."),
        ("Why did you select SQLite in WAL mode instead of PostgreSQL for this system?",
         "SQLite in WAL mode provides zero-daemon portability, full ACID transactions, and active SQL immutability triggers without requiring external background services. For local demonstration and multi-platform evaluation, it eliminates port conflicts, credential management, and service dependencies while maintaining strict relational integrity."),
        ("How does the platform prevent TOTP code replay attacks within the 30-second window?",
         "The database maintains an mfa_last_step integer column in the publishers table. When a valid 6-digit TOTP code is accepted for time step C, the system updates mfa_last_step = C. Any subsequent authentication request presenting a step <= mfa_last_step is immediately rejected, ensuring single-use semantics."),
        ("What happens to an offline player when a rollback is activated on the backend?",
         "An offline player continues playing their cached version safely without interruption. When the client reconnects to the network, the Service Worker and catalog sync detect that the backend deployment revision has advanced, prompting the client to update its active release pointer."),
        ("Why did you choose vanilla ECMAScript over modern frameworks like React and Vite?",
         "To eliminate opaque build abstractions, massive dependency trees (supply-chain attack surfaces), and AI-generated boilerplate. By utilizing standards-compliant ES modules, native Web APIs, and canvas 2D contexts, 100% of the codebase remains transparent, auditable, and permanent."),
        ("How does the Service Worker handle authenticated API requests?",
         "In web/sw.js, the fetch handler explicitly tests if (url.pathname.startsWith('/api/')) return; The worker never caches API responses, ensuring private credentials, tokens, and dynamic data are never stored in browser caches."),
        ("Explain the difference between an immutable release version and a deployment revision.",
         "A release version (e.g. 1.0.0, 1.0.1) is an immutable property of a static package artifact stored in the releases table. A deployment revision (1, 2, 3...) is a monotonic integer counter in the deployments table tracking the active pointer. Activating or rolling back advances the revision counter while pointing to an existing release."),
        ("How does the intake validator detect JavaScript syntax errors without executing code?",
         "The validator uses Node.js V8's native node:vm.Script API to compile the code into executable bytecode in memory. This validates AST syntax without executing any top-level statements, protecting the backend from hostile payloads."),
        ("What is the purpose of timingSafeEqual() in credential verification?",
         "Standard string comparisons return false as soon as the first mismatched byte is encountered, creating microsecond timing variances that allow attackers to infer credentials byte-by-byte. crypto.timingSafeEqual() executes in constant time across all bytes to defeat timing side-channel attacks."),
        ("Why does the Game Runtime CSP specify connect-src 'none'?",
         "To disable all outgoing network capabilities (fetch, XMLHttpRequest, WebSocket, WebRTC). This ensures that even if an untrusted game contains malicious logic, it is physically impossible to exfiltrate player data, mine cryptocurrencies, or communicate with external command servers."),
        ("How does the player client verify game integrity before launching?",
         "The client computes the SHA-256 digest of the game HTML and compares it against the signed manifest. It then uses the Web Cryptography API (window.crypto.subtle.verify) with the platform's ECDSA P-256 public key to verify the publisher's digital signature."),
        ("What is the role of the 8-second watchdog timer in runtime.js?",
         "When a game is launched, the watchdog initiates an 8,000ms countdown. If the game crashes, enters an infinite loop, or fails to emit an unplug:ready postMessage, the watchdog intercepts the failure, tears down the iframe, alerts the player, and logs telemetry."),
        ("How does UNPLUG comply with Google Play Store dynamic code execution policies?",
         "UNPLUG packages verified first-party games into the native Android assets directory (android/app/src/main/assets/public/) during the Gradle build, ensuring all default games are pre-bundled and statically auditable without violating dynamic code loading restrictions."),
        ("What happens if a publisher tries to delete a release record from the database?",
         "The database trigger trg_releases_prevent_delete intercepts the query and calls RAISE(ABORT, 'Release records are immutable'), causing the transaction to fail and preserving the audit trail."),
        ("Explain the difference between Cache-First and Network-First caching strategies.",
         "Network-First attempts to fetch from the server and falls back to cache on failure, introducing network latency on every request. Cache-First immediately returns the cached asset in under 5ms and updates in the background, which is essential for true offline-first performance."),
        ("How is the Base32 shared secret converted into a TOTP code in RFC 6238?",
         "The Base32 secret is decoded into bytes, hashed with the 8-byte time step counter C using HMAC-SHA1, truncated dynamically using the lower 4 bits of the 20th byte as an offset, and converted into a 31-bit integer modulo 10^6."),
        ("Why does UNPLUG avoid using external CDN scripts?",
         "Loading scripts from CDNs introduces third-party supply chain risks (if the CDN is compromised or blocked) and breaks offline operation. All scripts, fonts, and icons are vendor-hosted within the repository."),
        ("How does the platform prevent clickjacking attacks on the game runtime?",
         "The runtime host sends the HTTP header Content-Security-Policy: frame-ancestors 'self', which forbids external domains from framing the player."),
        ("What is the structure of the JSON registration envelope in a release package?",
         "It contains: { id, game_id, version, title, description, created_at, signature, sha256, manifest } where manifest specifies required permissions, orientation, and entry point."),
        ("Why does UNPLUG use IndexedDB instead of localStorage for offline game storage?",
         "localStorage is synchronous, blocks the main UI thread, and is limited to ~5MB of UTF-16 strings. IndexedDB is asynchronous, transaction-safe, and supports hundreds of megabytes of structured binary Blobs."),
        ("Explain how the Emergency Rollback Drill proves zero-downtime recovery.",
         "When release 1.0.1 causes a crash, the administrator clicks 'Activate 1.0.0'. The backend advances revision from 2 to 3, repointing active_release_id to 1.0.0 in SQLite. The player application detects the update on next ping and switches back in under one second without code compilation or server restarts."),
        ("How does the dual-iframe containment architecture work?",
         "The outer page hosts the player controls. Inside sits an intermediary runtime host (Port 3000), which hosts the inner sandboxed game iframe (unique null origin). This double boundary ensures total isolation between the game and the top window."),
        ("What is the significance of the monotonic revision counter in release governance?",
         "It prevents rollback ambiguity. Even though the system rolls back to an older version (1.0.0), the deployment revision strictly increases (e.g. 1 -> 2 -> 3), ensuring clients can clearly distinguish between a rollback and an outdated cache."),
        ("How are touch and keyboard inputs normalized in the Bounce mini-game?",
         "Event listeners for pointerdown, pointermove, and pointerup normalize mouse, stylus, and touch coordinates against canvas.getBoundingClientRect() with touch-action: none, preventing browser pull-to-refresh gestures."),
        ("What telemetry metrics does UNPLUG capture, and why are they anonymous?",
         "UNPLUG captures game_id, release_id, event_type ('launch', 'score', 'crash', 'watchdog_timeout'), and value. No IP addresses, device identifiers, or user tracking cookies are stored, upholding privacy-by-design."),
        ("How does Capacitor bridge the web application to native Android?",
         "Capacitor creates a native Android project with a custom WebView (BridgeWebView) that intercepts asset requests and serves them directly from Android local storage (assets/public/), enabling 100% offline execution without internet permissions."),
        ("What are the key security flags enabled in the Windows Electron desktop build?",
         "contextIsolation: true, nodeIntegration: false, sandbox: true, webSecurity: true, and safe navigation handlers blocking external URLs."),
        ("Why is UNPLUG considered an exemplary Major Engineering Capstone Project?",
         "Because it addresses real-world industrial failures (CrowdStrike, SolarWinds, App Store monopolies) through rigorous computer science principles: formal cryptography (RFC 6238, P-256), relational ACID immutability, zero-trust web sandboxing, and full multi-platform offline delivery.")
    ]

    for i, (q, a) in enumerate(viva_qa, 1):
        b.callout(f"VIVA QUESTION {i}", q, f"Authoritative Architectural Defense: {a}", "25458C", "EFF6FF")
